[build]
  command = "npm run build"
  publish = "dist"

[dev]
  command = "npm run dev"
  port = 5173
  targetPort = 5173

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  VITE_GOOGLE_AI_API_KEY = "AIzaSyAAaNkc4OOGh1uhnMro1i8xvj20XOWUBJc"